apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-app
  namespace: default
  labels:
    app: flask-app
spec:
  endpoints:
  - port: metrics
    interval: 5s
  selector:
    matchLabels:
      app: flask-app
  namespaceSelector:
    matchNames:
      - default      