# Servicio para exponer la app
apiVersion: v1
kind: Service
metadata:
  name: svc-load-app-flask
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 8181
    targetPort: 8181
