apiVersion: v1
kind: ConfigMap
metadata:
  name: cfm-init-{{ .Values.db.name }}-{{ include "flask-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  crud_flask.sql: |
{{ .Values.db.initdb | indent 4 }}