# mysql-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}-service
spec:
  selector:
    app: {{ .Values.db.name }}
  ports:
    - port: {{ .Values.db.port }}
  clusterIP: None