# flask-app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-app-{{ include "flask-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
      {{- include "flask-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
        {{- include "flask-app.selectorLabels" . | nindent 8 }} 
    spec:
      containers:
      - name: {{ .Values.labels.app }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sec-db-{{ .Values.db.name }}-{{ include "flask-app.fullname" . }}
              key: mysql_user_password
        envFrom:
        - configMapRef:
            name: cfm-app-{{ include "flask-app.fullname" . }}