replicas: 1
image:
  repository: jesusod/python-app
  tag: latest
  pullPolicy: Always

labels:
  app: flask-app

service:
  port: 8181
  type: NodePort
  nodePort: 30001

configmap:
  name: mysql-preload-data-config

pv:
  capacity:
    storage: 20Gi
  accessModes: ReadWriteOnce
  
env:
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_USER_PASSWORD: ZGV2
  MYSQL_USER: dev
  MYSQL_PASSWORD: ZGV2
  MYSQL_DB: crud_flask
  MYSQL_HOST: svc-db-mysql

db:
  name: mysql
  replicas: 1
  image:
    repository: mysql
    tag: "5.5"
  port: 3306
  initdb: |
    -- phpMyAdmin SQL Dump
    -- version 4.4.15.7
    -- http://www.phpmyadmin.net
    --
    -- Host: localhost
    -- Generation Time: Jan 30, 2017 at 10:34 AM
    -- Server version: 5.7.17-0ubuntu0.16.04.1
    -- PHP Version: 7.0.13-0ubuntu0.16.04.1

    SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
    SET time_zone = "+00:00";


    /*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
    /*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
    /*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
    /*!40101 SET NAMES utf8mb4 */;

    --
    -- Database: `crud_flask`
    --
    CREATE DATABASE IF NOT EXISTS crud_flask;
    USE crud_flask;
    -- --------------------------------------------------------

    --
    -- Table structure for table `phone_book`
    --

    CREATE TABLE IF NOT EXISTS `phone_book` (
      `id` int(5) NOT NULL,
      `name` varchar(255) NOT NULL,
      `phone` varchar(50) NOT NULL,
      `address` varchar(255) NOT NULL
    ) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=latin1;

    --
    -- Dumping data for table `phone_book`
    --

    INSERT INTO `phone_book` (`id`, `name`, `phone`, `address`) VALUES
    (16, 'Muhammad Hanif', '085733492411', 'Lamongan');

    --
    -- Indexes for dumped tables
    --

    --
    -- Indexes for table `phone_book`
    --
    ALTER TABLE `phone_book`
      ADD PRIMARY KEY (`id`);

    --
    -- AUTO_INCREMENT for dumped tables
    --

    --
    -- AUTO_INCREMENT for table `phone_book`
    --
    ALTER TABLE `phone_book`
      MODIFY `id` int(5) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=21;
    /*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
    /*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
    /*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

