apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}-pv-volume
  labels:
    type: local
spec:
  storageClassName: {{ .Values.pv.storageClass }}
  capacity:
    storage: {{ .Values.pv.capacity.storage }}
  accessModes:
    - {{ .Values.pv.accessModes }}
  hostPath:
    path: {{ .Values.pv.hostpath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pv.name }}-pv-claim
spec:
  storageClassName: {{ .Values.pv.storageClass }}
  accessModes:
    - {{ .Values.pv.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pv.capacity.storage }}